language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'create database test_palette_picker;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: K5UVlckFmjWQlvNtQ1fU+mU7EB8wlysPxt831epOjTmcvx/OcV1ntHdJsxfojWJA6vEoP0RcK0UeQZHlFshEWevDpPOk5UxJ2n2sf4W62nQYKyZVtuR1g3Mo0UZPIRmAxUJAxCeQXV7CU5ADRw8/r+/MCJN8H1OiR0jab0wvkFe7uEFYWcsrv79Rl2ZiVpK32duvrnXLCS34kX7Ex9asH0qHVlhegoAmDvvkrrH9x0oA80++XRgH0SGsSFBsZNWBAa217dg8y9Ir4Im+snqw6z4qfIPUn3uzRluLvix5T7nYNXViFC3P2jJUFyvQOJM+wfghWIbyhkeM3OJw+0Lp0fMng/dwCGr/iXh4+Tf1gPGW5JSmhbe1XgRW1+M3AOw18yV0vgnOZTDSMu4oaFQD4WJCiXUDT0qPcW+i+Y4M6cH9pOs6WKG6YnOtoqKvVy2xXoYD5HeQEMh3Bw5e+CaAAPfCHS5pl/Dd/k0dWnpTxKnZ9bi0kgwxV9DcmCjSJCPxnh7ml0tocabp6X2l1MwS6UsvkcEYqGPZ8cOzfhQbuoXtzPZPolQRa5cSbhwG/hrNDMFphmK+ATb2mAAkum1vwvw2E8g4cjgGWnoJit7DblhDZghbpH+vcYq1FjW7l2/zEjwli/YproXAAUwxJVYqPApeb/y0VeIZJewCcxW33F0=
    app: dsd-palette-picker