language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'create database test_palette_picker;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: RPYfxGwe6X0JqNSiLCUSFypjeRHkfuJe1LZAA2pQZwJ2tc8jH540zi3QH2UzQ+630IOn923d4eqFaSiHp/KznqvoLBDBd3PjN9RsLRGjE0ZZZ828HoQHkAj6agfWVwjz+s5EJy7XHjXEDV2DuvlMmV0Sj/3w1xyAW6cWWfYA4LKrZWT05KjsGnigl7Nx7cYhUaxg2SedvLin2vDvfP6PL5jp+34nL9gvRCsBLEetSE+5VZhOZsnNWxEdwEvOoRE3/WZx023sDCl212aUtI0+fxtrSWsnIQkSVihJJUNIsDsdbxGHSaNk6vmMasoSYKW8R87imYwoHurLJl8q5kQRKtEbpp3JxrzrSwhCz/7mJp4Uznu3wjseKXODRwYwPbMKiVTc5AcHqoueiQSJXU1kuayomRelZQgl3aBgBiT5sdHbAect/2eu+S4lAP+AzKK5HVOh78HccBCF7BHuX4KjClDvEsqI7KUgcX9J/0aROT+JNEnXmbytWY+4qiI6FPfvG/vvEXbkB3aXEF/iph4H3J7XAJdWn9OkD+qFTN/zcVjxRh9YZjgVTID/qvfbqu0UM5+0V2fVGnlQFoJqm6NVFTtzTJvmQo8mQlOqY2RcCgi9J6XvxVAY+D/OjA5DHaP+B4HZn1gSToZ/IoNueh1oSIPGsf6c9lCugX/jZbWFyxo=
  app: dsd-palette-picker
  on:
    repo: dsdunn/pallete-picker
